# Generated by Django 4.2.4 on 2023-10-10 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IrrigationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plant_id", models.IntegerField(default=0)),
                ("volume", models.FloatField()),
                ("timestamp", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("is_empty", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plant_id", models.IntegerField(default=0)),
                ("humidity", models.FloatField()),
                ("temperature", models.FloatField()),
                ("timestamp", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                ("plant_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="Flower", max_length=255)),
                ("humidity_low", models.FloatField()),
                ("humidity_high", models.FloatField()),
                ("temperature_low", models.FloatField()),
                ("temperature_high", models.FloatField()),
                ("description", models.CharField(max_length=255)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smart_agriculture.product",
                    ),
                ),
            ],
        ),
    ]
