# Generated by Django 4.2.4 on 2023-10-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smart_agriculture", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
    ]
