# Generated by Django 4.2.4 on 2023-10-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smart_agriculture", "0002_alter_plant_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="product_id",
            field=models.IntegerField(default=0),
        ),
    ]
