# Generated by Django 4.2.5 on 2023-10-18 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_agriculture', '0003_alter_plant_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(default='', max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('content', models.CharField(default='', max_length=255)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_agriculture.plant')),
            ],
        ),
    ]
