# Generated by Django 4.2.4 on 2023-10-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smart_agriculture", "0005_plant_status_alter_plant_plant_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="history",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Flower", max_length=255)),
                ("product_id", models.IntegerField(default=0)),
                ("description", models.CharField(default="", max_length=255)),
                ("status", models.CharField(max_length=30)),
            ],
        ),
    ]
