# Generated by Django 4.2.4 on 2023-10-29 04:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("smart_agriculture", "0006_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="content",
        ),
    ]
